### PR TITLE
renames all "ios" tabs to "obj-c"

### PR DESCRIPTION
**Pull request by andrewxhill**
Screen Shot 2019-05-20 at 8 01 25 AM

makin space for swift tabs :)

### CODE REVIEW

**Comment by andrewxhill** [comment]
okay, highlighting leaves something to be desired, but it's all there now

**Comment by asutula** [comment]
Ah, I thought "iOS" was fine for the tab name, I just thought if the template was doing syntax highlighting based on the specified language, we should specify Obj C if possible.

**Comment by andrewxhill** [comment]
We can change back to iOS, but wouldn't we split it again once we get swift examples in there?

**Comment by asutula** [comment]
Guess it depends on how far we want to take these snippets. Should we split Android into Java and Kotlin as well? Seems like overkill to me. Maybe one language per platform is enough.

**Comment by andrewxhill** [comment]
I thought Java/Kotlin was more like the Typescript/Javascript distinction. So I guess the question is, can you use ObjC examples directly in a swift app or would you need to expose Textile in a more swifty way?

**Comment by asutula** [comment]
My understanding is Kotlin is a totally different language. Need to research more tho.

Swift applications can include Obj C code if the developer chooses (as in, the developer can write their own Obj C code). The Textile is callable directly from Swift code, though, so it's not a requirement that the developer write Obj C code to interact with Textile.

Just bumping up to a slightly higher level... I think exhaustive language examples are useful for code that is meant to be copy/pasted into a project, to make integration of a library faster/easier, for example. Like copying a pasting some initialization code that includes your API key and app bundle id.

I don't think the code in these example is that. They are just general examples of things Textile can do if you want to do them. It makes sense to provide an example on each platform because the APIs look and feel different enough on each platform. But within a single mobile platform, the APIs are the same no matter which language you use. Of course they look different because of the different language, but the mechanics are the same.

**Comment by andrewxhill** [comment]
Ok, we are coming at it from a different understanding. People are copy/pasting the Tour and it was written to encourage that exactly. While mobile will get trickier to cut and paste, I think it's really valuable to include the flexibility of our APIs in the first doc most developers are going to land on. 

So if a Swift developer could use Textile in pure swift, and we've already got that built in, I see it as pretty valuable to just include the Swift tab in the tour directly.

**Comment by asutula** [comment]
Ah ok didn't realize that was the intention. Just hard to decide where to draw the line then. Kotlin? CoffeeScript? Javascript? (searching frantically for this compile-to-javascript language that is made up of only space and tab characters... but ok just would be trolling then haha).

But really, I'm cool with the Obj C + Swift split if that's what you think is best.

**Comment by andrewxhill** [comment]
I don't know the right split! Just the _too many languages_ documented as a downside, I don't see yet. Seems like Swift is different enough from ObjC and we already have support out of box, so it could be nice to just showcase that API up front.

**Pull request merged**
