### PR TITLE
Add destroy commands and make minor changes consistent with command help

### PR DESCRIPTION
**Pull request by adgitate1**
Here is the script I used in case it is helpful to do again in the future:

(named ./compare_docs.sh)
```shell
#!/bin/sh
set -x
if [[ "$INDOCKER" = true ]]; then
	apk add perl
	cd ./compare_docs/textile/cmd/tt
	wget https://raw.githubusercontent.com/spf13/cobra/0ab5b6bcfcde193577634059f6f211c850a456ec/doc/md_docs.go
	wget https://raw.githubusercontent.com/spf13/cobra/1e58aa3361fd650121dceeedc399e7189c05674a/doc/util.go
	sed -i '14s/doc/main/' util.go
	sed -i '14s/doc/main/' md_docs.go
	sed -i '67s/##/#/' md_docs.go
	sed -i '67s/name/strings.Replace(name, "tt ", "", 1)/' md_docs.go
	sed -i '24d;40,44d;68,69d;111,114d' md_docs.go
	perl -0777 -pi.bak -e 's/(.+)("time")/$1$2\n$1"log"/' main.go
	perl -0777 -pi.bak -e 's[(func main.+?)^}][$1\terr := GenMarkdownTree(rootCmd, "../../../docs/docs/hub/cli")\n\tif err != nil {log.Fatal(err)}\n}]sm' main.go
	rm ../../../docs/docs/hub/cli/*
	go run .
	chown -R --reference=../../../docs/docs/hub/cli/ ../../../docs/docs/hub/cli
	#/bin/ash
else
	mkdir compare_docs
	cd compare_docs
	git clone https://github.com/textileio/textile.git
	#replace https://github.com/textileio/docs.git with your forked the docs repo
	git clone https://github.com/adgitate1/docs.git
	cd ..
	sudo docker run --rm -it -v $(pwd):/go -e "INDOCKER=true" golang:alpine ./compare_docs.sh
	cd compare_docs/docs/docs/hub/cli
	git add -AN #add all files without content (to get untracked)
	git add -p . #review lines, use ? for help
	git commit .
	#git push origin master
fi
```

### CODE REVIEW

**Comment by andrewxhill** [comment]
Lovely! 

Could you add the DCO signoff here, https://github.com/textileio/docs/pull/137/checks?check_run_id=676002053

**Comment by adgitate1** [comment]
It is now signed.

**Comment by andrewxhill** [comment]
annnd you are live! https://docs.textile.io/hub/cli/tt_destroy/ thanks again

i'll revisit the sh script later to see if i can add it to the deploy step (though first need to migrate this to a textile bucket)

**Comment by adgitate1** [comment]
Cool.

The only problem with completely automating when deploying without manual review is overwriting changes people made directly to the markdown.  [example](https://github.com/textileio/docs/pull/135/files).  Unless we want to make and [document](https://github.com/textileio/docs/blob/master/CONTRIBUTING.md) a new policy that the cli files are automatically generated and shouldn't be directly modified so they stay consistent. (suggested [here](https://github.com/textileio/docs/pull/130#issuecomment-624292352))

**Pull request merged**
